// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAPISql;

#nullable disable

namespace TestAPISql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestAPISql.Modules.Users.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@mail.ru",
                            Login = "My_Log!n",
                            Name = "Test1",
                            Password = "Password!1234",
                            Token = "123dswqefdfae3fgq"
                        },
                        new
                        {
                            Id = 2,
                            Email = "test@mail.ru",
                            Login = "My_Log!n",
                            Name = "Test2",
                            Password = "Password!1234",
                            Token = "123dswqefdfae3fgq"
                        },
                        new
                        {
                            Id = 3,
                            Email = "test@mail.ru",
                            Login = "My_Log!n",
                            Name = "Test3",
                            Password = "Password!1234",
                            Token = "123dswqefdfae3fgq"
                        },
                        new
                        {
                            Id = 4,
                            Email = "test@mail.ru",
                            Login = "My_Log!n",
                            Name = "Test4",
                            Password = "Password!1234",
                            Token = "123dswqefdfae3fgq"
                        },
                        new
                        {
                            Id = 5,
                            Email = "test@mail.ru",
                            Login = "My_Log!n",
                            Name = "Test5",
                            Password = "Password!1234",
                            Token = "123dswqefdfae3fgq"
                        },
                        new
                        {
                            Id = 6,
                            Email = "test@mail.ru",
                            Login = "My_Log!n",
                            Name = "Test6",
                            Password = "Password!1234",
                            Token = "123dswqefdfae3fgq"
                        },
                        new
                        {
                            Id = 7,
                            Email = "test@mail.ru",
                            Login = "My_Log!n",
                            Name = "Test7",
                            Password = "Password!1234",
                            Token = "123dswqefdfae3fgq"
                        },
                        new
                        {
                            Id = 8,
                            Email = "test@mail.ru",
                            Login = "My_Log!n",
                            Name = "Test8",
                            Password = "Password!1234",
                            Token = "123dswqefdfae3fgq"
                        },
                        new
                        {
                            Id = 9,
                            Email = "test@mail.ru",
                            Login = "My_Log!n",
                            Name = "Test9",
                            Password = "Password!1234",
                            Token = "123dswqefdfae3fgq"
                        },
                        new
                        {
                            Id = 10,
                            Email = "test@mail.ru",
                            Login = "My_Log!n",
                            Name = "Test10",
                            Password = "Password!1234",
                            Token = "123dswqefdfae3fgq"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
